import '@fortawesome/fontawesome-free/css/all.min.css'
import './utils/layout.scss'
import './utils/display.scss'
import './layouts/middle-layout.scss'
import './components/menu.scss'
import './components/button.sass'
import './components/input.sass'
import './App.sass'