import '@fortawesome/fontawesome-free/css/all.min.css'
import './bulma/bulma.scss'
import './utils/format.scss'
import './utils/layout.scss'
import './utils/display.scss'
import './layouts/middle-layout.scss'
import './components/menu.scss'
import './App.scss'