// import 'bulma/css/bulma.min.css'
import './bulma.scss'
import '@fortawesome/fontawesome-free/css/all.min.css'
import './format.scss'
import './layout.scss'
import './display.scss'
import './App.scss'